const USER_INPUT_FOCUS = "USER_INPUT_FOCUS";
const USER_INPUT_LOST_FOCUS = "USER_INPUT_LOST_FOCUS";
const USER_INPUT_RECEIVED = "USER_INPUT_RECEIVED";
const USER_INPUT_VALIDATE = "USER_INPUT_VALIDATE";
const SET_ERROR_INPUT = "SET_ERROR_INPUT";
const CLEAR_ERRORS = "CLEAR_ERRORS";

export { USER_INPUT_FOCUS, USER_INPUT_LOST_FOCUS, USER_INPUT_RECEIVED, USER_INPUT_VALIDATE, SET_ERROR_INPUT, CLEAR_ERRORS }
