const USER_INPUT_RECEIVED = "USER_INPUT_RECEIVED";
const SET_ERROR_INPUT = "SET_ERROR_INPUT";
const CLEAR_ERROR = "CLEAR_ERROR";
const LOAD_FIELDS = "LOAD_FIELDS";
const SET_AS_VALIDATED = "SET_AS_VALIDATED";

export { USER_INPUT_RECEIVED, SET_ERROR_INPUT, CLEAR_ERROR, LOAD_FIELDS, SET_AS_VALIDATED }
